[format]
	[format.rules]
		indent-style                    = "tab"  # or "space"
		indent-sub-tables               = true
		indent-table-key-value-pairs    = true
		indent-width                    = 2
		key-value-equals-sign-alignment = true
		trailing-comment-alignment      = true
		trailing-comment-space-width    = 2
